# All the mods with an id matching any of the regular expressions in this list will be excluded from the generated splash texts
ignore_modid_regexs = ["java", "minecraft", "quilt_.*", "quilted_fabric_.*", ".*api.*"]
# This templates are used to generate the splash texts. Some patterns are replaced:
# @@MOD@@ will be replaced with a mod's name
# @@VERSION@@ will be replaced with a mod's version
# If various replace patterns are used in a template, they will refer to the same mod
splash_templates = ["Now featuring @@MOD@@!", "With @@MOD@@ version @@VERSION@@!", "@@MOD@@???? Cool!", "Can't play without @@MOD@@!", "Who's at version @@VERSION@@? That's right, @@MOD@@!", "Did you ever play before with @@MOD@@?", "@@MOD@@ is @@MOD@@", "If you liked @@MOD@@, it's authors will love to hear about it!"]
# Set this option to false to enable seasonal splash texts (for Christmas, New year, and Halloween)
# default: false
skip_seasonal_splash_text = false
# The special PLAYER IS YOU splash text will be enabled if this value is set to 24
# default: 0
the_answer = 0
# If you want to see the original splash texts alongside the ones generated by the mod, set this option to true
# default: false
keep_old_splashes = true
