enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingDepth = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true
